### PR TITLE
Update to v1.7.0

### LINKED ISSUE #5: Package is out of date
[sources are no longer published on pypi](https://github.com/letmaik/lensfunpy/issues/25), so the recipe needs updating accordingly

### PR DESCRIPTION
**Pull request by Anthchirp**
Have a go at updating this.

Fixes #5 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by Anthchirp** [comment]
Ready for review/merging. Adding myself as maintainer, assuming that you don't mind. If you do then feel free to remove that commit again.

@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
@conda-forge/lensfunpy can you look at this one?

**Comment by Anthchirp** [comment]
@beckermr still no reaction. Want to merge this one directly?

**Pull request merged**
